A2A.MI: A2a-1
ACE.MI: Acea-Spa
AZM.MI : Azimut-Holding-S.p.a
BGN.MI: Banca-Generali-Spa
BMED.MI: Banca-Mediolanum-S.p.a
BPE.MI: Bper-Banca-Spa
BRE.MI: Brembo
BZU.MI: Buzzi-Unicem
CRES.MI: Coima-Srl
ENEL.MI: Enel
ENI.MI: Eni-Recensioni-E3164.htm
FCT.MI: Fincantieri
G.MI: Generali
HER.MI: Gruppo-Hera
IG.MI: Italgas
IRE.MI: Iren
ISP.MI: Intesa-Sanpaolo
LDO.MI: Leonardo-Recensioni-E10756.htm
MB.MI: Mediobanca
MT.MI: Maire-Tecnimont-Recensioni-E484397.htm
PIRC.MI: Pirelli
PRT.MI: Esprinet
PST.MI: Poste-Italiane
SPM.MI: Saipem
SRG.MI: Snam
STLA.MI : Stellantis
TEN.MI: Tenaris
TITR.MI: Tim
TRN.MI: Terna
UCG.MI : Unicredit
UNI.MI: Unipol-Gruppo-Finanziario-S.p.a.-1
WBD.MI: Salini--impregilo
ZV.MI: Zignago-Vetro-Spa
