A2A.MI: a2a
ACE.MI: acea-spa
AZM.MI : azimutgroup
BGN.MI: banca-generali
BMED.MI: banca-mediolanum
BPE.MI: bper-banca
BRE.MI: brembo-s-p-a
BZU.MI: buzzi-unicem
CRES.MI: coima
ENEL.MI: enelgroup
ENI.MI: eni
FCT.MI: fincantieri
G.MI: generali
HER.MI: gruppo-hera
IG.MI: italgas
IRE.MI: iren-gruppo
ISP.MI: intesa-sanpaolo
LDO.MI: leonardo_company
MB.MI: mediobanca
MT.MI: maire-tecnimont
PIRC.MI: pirelli
PRT.MI: esprinet
PST.MI: poste-italiane
SPM.MI: saipem
SRG.MI: snam-s-p-a-
STLA.MI : stellantis
TEN.MI: tenaris
TITR.MI: tim
TRN.MI: terna
UCG.MI : unicredit
UNI.MI: unipol-gruppo
WBD.MI: webuildgroup
ZV.MI: zignago-vetro-spa
