AZM.MI : azimutgroup
BMED.MI: banca-mediolanum
CRES.MI: coima
ENI.MI: eni
FCT.MI: fincantieri
G.MI: generali
IRE.MI: iren-gruppo
IG.MI: italgas
LDO.MI: leonardo_company
PST.MI: poste-italiane
SRG.MI: snam-s-p-a-
TITR.MI: tim
STLA.MI : stellantis
ENEL.MI: enelgroup
UCG.MI : unicredit
TRN.MI: terna
UNI.MI: unipol-gruppo
BGN.MI: banca-generali
WBD.MI: webuildgroup
SPM.MI: saipem
MT.MI: maire-tecnimont
A2A.MI: a2a
